"""user role

Revision ID: 15c801ad2f86
Revises: b7cbada9f70c
Create Date: 2021-01-19 21:47:22.544620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c801ad2f86'
down_revision = 'b7cbada9f70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('GUEST', 'USER', 'ADMIN', name='role'), nullable=False,server_default='USER'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
